name: CI check test
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  # Only run when the matrix tests are done
  workflow_run:
    workflows:
      - "CI"
    types:
      - completed

env:
  NXF_ANSI_LOG: false
  CAPSULE_LOG: none

jobs:
  test:
    name: Check results of pipeline run with test data
    # Only run on push if this is the nf-core dev branch (merged PRs)
    runs-on: ubuntu-latest
    strategy:
      # This tells github to continue running other profile tests if some tests fail (default cancels all tests upon failure)
      fail-fast: false
    steps:
      - name: Check if Dockerfile or Conda environment changed
        uses: technote-space/get-diff-action@v4
        run: |
          md5sum -c hash_test.txt > hash_test_result.txt
          if [ grep FAILED hash_test_result.txt ]; then
            echo "The md5sum test failed because of the following file(s):"
            grep FAILED hash_test_result.txt
          else
            exit 0
          fi


