repository_type: pipeline
nf_core_version: "2.14.1"

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .gitignore
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - docs/README.md
    - LICENSE

  files_exist:
    - lib/nfcore_external_java_deps.jar

  nextflow_config:
    - manifest.name
    - manifest.homePage
    - config_defaults:
        - params.custom_config_base
        - params.report_file
        - params.references_file
        - params.css
        - params.logo

  multiqc_config:
    - report_comment # otherwise throws error: multiqc_config: 'assets/multiqc_config.yml' does not contain a matching 'report_comment'.
