# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
# use this to find packages: https://anaconda.org/
name: qbic-pipelines-rnadeseq-2.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-deseq2=1.34.0 
  - bioconductor-genefilter=1.76.0  
  - bioconductor-genomeinfodbdata=1.2.7   
  - bioconductor-org.hs.eg.db=3.14.0 
  - bioconductor-org.mm.eg.db=3.14.0 
  - bioconductor-pathview=1.34.0   
  - bioconductor-vsn=3.62.0
  - pandoc=2.17.1.1
  - r-base=4.1.2
  - r-dplyr=1.0.7
  - r-dt=0.20 
  - r-extrafont=0.17
  - r-formattable=0.2.1
  - r-ggplot2=3.3.5
  - r-gplots=3.1.1
  - r-gprofiler2=0.2.1
  - r-kableextra=1.3.4
  - r-knitr=1.37
  - r-optparse=1.7.1
  - r-pheatmap=1.0.12
  - r-plyr=1.8.6
  - r-reshape2=1.4.4
  - r-rmarkdown=2.11
  - r-svglite=2.1.0
  - r-tidyverse=1.3.1
  - r-yaml=2.2.2
